DROP TABLE IF EXISTS users;
CREATE TABLE users
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    username varchar(50)                                         NOT NULL,
    password varchar(50)                                         NOT NULL,
    CONSTRAINT username UNIQUE (username)
);
